# Generated by Django 5.2.8 on 2025-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=255)),
                ('file_key', models.CharField(max_length=512)),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'chathistory',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Customuser',
        ),
    ]
